# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(300, 300)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.vk_login = QtWidgets.QLineEdit(self.centralwidget)
        self.vk_login.setObjectName("vk_login")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vk_login)
        self.vk_password = QtWidgets.QLineEdit(self.centralwidget)
        self.vk_password.setObjectName("vk_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vk_password)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)
        self.about_button = QtWidgets.QPushButton(self.centralwidget)
        self.about_button.setObjectName("about_button")
        self.verticalLayout.addWidget(self.about_button)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.outputText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.outputText.setObjectName("outputText")
        self.verticalLayout.addWidget(self.outputText)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "VK SCOUT DESKTOP"))
        self.label.setText(_translate("LoginWindow", "Аккаунт ВК"))
        self.label_2.setText(_translate("LoginWindow", "Логин"))
        self.label_3.setText(_translate("LoginWindow", "Пароль"))
        self.login_button.setText(_translate("LoginWindow", "Войти"))
        self.about_button.setText(_translate("LoginWindow", "О программе"))
        self.label_4.setText(_translate("LoginWindow", "Вывод:"))
